version: '3.5'

services:
  ogmios:
    image: cardanosolutions/ogmios:latest-${NETWORK:-testnet}
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/relaynode1/db/socket",
      "--node-config", "/relaynode1/testnet-config.json"
    ]
    volumes:
      - ${RELAYNODE_VOL:-/home/ubuntu/cardano-my-node/relaynode1/}:/relaynode1
    ports:
      - ${OGMIOS_PORT:-1337}:1337
